create table if not exists public.salah_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  salah_name text not null,
  focus_rating integer not null check (focus_rating between 1 and 5),
  distractions text not null default '',
  reflection_text text not null default '',
  logged_at bigint not null,
  log_date date not null,
  from_salah_mode boolean not null default false,
  reminder_type text,
  classified_category text
);

alter table public.salah_logs add column if not exists reflection_text text not null default '';
alter table public.salah_logs add column if not exists reminder_type text;
alter table public.salah_logs add column if not exists classified_category text;

-- Older clients inserted a replacement log rather than updating it. Keep the
-- newest one before enforcing the idempotent sync key.
delete from public.salah_logs as older
using public.salah_logs as newer
where older.user_id = newer.user_id
  and older.salah_name = newer.salah_name
  and older.log_date = newer.log_date
  and (
    older.logged_at < newer.logged_at
    or (older.logged_at = newer.logged_at and older.ctid < newer.ctid)
  );

create unique index if not exists salah_logs_user_salah_date_key
  on public.salah_logs (user_id, salah_name, log_date);

alter table public.salah_logs enable row level security;

drop policy if exists "Users manage their own salah logs" on public.salah_logs;
create policy "Users manage their own salah logs"
  on public.salah_logs for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
